# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='word',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
